import { backspace, enter, del, tab, goLeft, goRight, goUpDown, empty } from "./keyboard-functions.js";

export const width_base = 80;
export const height_base = 80;

export const gap = 12;

export const style_base_button = "#265c6a";
export const style_active_button = "#3eb4b9";
export const style_space_button = "#265c6a";

export const arr = [
  //////////////  1 ряд /////////////////////////
  {
    width: width_base,
    height: height_base,
    style: style_space_button,
    x: gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "IntlBackslash",
    letter: { rus: "ё", en: "`" },
    letterUp: { rus: "Ё", en: "~" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 1 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit1",
    letter: { rus: "1", en: "1" },
    letterUp: { rus: "!", en: "!" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 2 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit2",
    letter: { rus: "2", en: "2" },
    letterUp: { rus: '"', en: "@" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 3 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit3",
    letter: { rus: "3", en: "3" },
    letterUp: { rus: "№", en: "#" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 4 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit4",
    letter: { rus: "4", en: "4" },
    letterUp: { rus: ";", en: "$" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 5 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit5",
    letter: { rus: "5", en: "5" },
    letterUp: { rus: "%", en: "%" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 6 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit6",
    letter: { rus: "6", en: "6" },
    letterUp: { rus: ";", en: "^" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 7 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit7",
    letter: { rus: "7", en: "7" },
    letterUp: { rus: "?", en: "&" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 8 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit8",
    letter: { rus: "8", en: "8" },
    letterUp: { rus: "*", en: "*" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 9 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit9",
    letter: { rus: "9", en: "9" },
    letterUp: { rus: "(", en: "(" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 10 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Digit0",
    letter: { rus: "0", en: "0" },
    letterUp: { rus: ")", en: ")" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 11 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Minus",
    letter: { rus: "-", en: "-" },
    letterUp: { rus: "_", en: "_" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: (width_base + gap) * 12 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Equal",
    letter: { rus: "=", en: "=" },
    letterUp: { rus: "+", en: "+" },
  },
  {
    width: width_base * 2.5,
    height: height_base,
    style: style_space_button,
    x: (width_base + gap) * 13 + gap,
    y: 10,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Backspace",
    letter: { rus: "Backspace", en: "Backspace" },
    letterUp: { rus: "Backspace", en: "Backspace" },
    function: backspace,
  },
  //////////////  2 ряд /////////////////////////
  {
    width: width_base * 1.5 + gap / 2,
    height: height_base,
    style: style_space_button,
    x: gap,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Tab",
    letter: { rus: "Tab", en: "Tab" },
    letterUp: { rus: "Tab", en: "Tab" },
    function: tab,
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyQ",
    letter: { rus: "й", en: "q" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 1,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyW",
    letter: { rus: "ц", en: "w" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 2,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyE",
    letter: { rus: "у", en: "e" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 3,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyR",
    letter: { rus: "к", en: "r" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 4,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyT",
    letter: { rus: "е", en: "t" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 5,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyY",
    letter: { rus: "н", en: "y" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 6,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyU",
    letter: { rus: "г", en: "u" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 7,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyI",
    letter: { rus: "ш", en: "i" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 8,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyO",
    letter: { rus: "щ", en: "o" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 9,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyP",
    letter: { rus: "з", en: "p" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 10,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "BracketLeft",
    letter: { rus: "х", en: "[" },
    letterUp: { rus: "Х", en: "{" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 11,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "BracketRight",
    letter: { rus: "ъ", en: "]" },
    letterUp: { rus: "Ъ", en: "}" },
  },
  {
    width: width_base * 1.95,
    height: height_base,
    style: style_space_button,
    x: gap * 2.5 + width_base * 1.5 + (width_base + gap) * 12,
    y: gap + height_base + gap,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Delete",
    letter: { rus: "Del", en: "Del" },
    letterUp: { rus: "Del", en: "Del" },
    function: del,
  },
  //////////////  3 ряд /////////////////////////
  {
    width: width_base * 1.8,
    height: height_base,
    style: style_space_button,
    x: gap,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "CapsLock",
    letter: { rus: "Caps", en: "Caps" },
    letterUp: { rus: "Caps", en: "Caps" },
    active: false,
    function: empty,
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 0,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyA",
    letter: { rus: "ф", en: "a" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyS",
    letter: { rus: "ы", en: "s" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 2,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyD",
    letter: { rus: "в", en: "d" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 3,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyF",
    letter: { rus: "а", en: "f" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 4,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyG",
    letter: { rus: "п", en: "g" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 5,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyH",
    letter: { rus: "р", en: "h" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 6,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyJ",
    letter: { rus: "о", en: "j" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 7,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyK",
    letter: { rus: "л", en: "k" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 8,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyL",
    letter: { rus: "д", en: "l" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 9,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Semicolon",
    letter: { rus: "ж", en: ";" },
    letterUp: { rus: "Ж", en: ":" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 10,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Quote",
    letter: { rus: "э", en: "'" },
    letterUp: { rus: "Э", en: '"' },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 11,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Backslash",
    letter: { rus: "\\", en: "\\" },
    letterUp: { rus: "/", en: "|" },
  },
  {
    width: width_base * 1.7,
    height: height_base,
    style: style_space_button,
    x: gap * 2 + width_base * 1.8 + (width_base + gap) * 12,
    y: gap + (height_base + gap) * 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Enter",
    letter: { rus: "Enter", en: "Enter" },
    letterUp: { rus: "Enter", en: "Enter" },
    function: enter,
  },
  //////////////  4 ряд /////////////////////////
  {
    width: width_base * 2.5,
    height: height_base,
    style: style_space_button,
    x: gap,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ShiftLeft",
    letter: { rus: "Shift", en: "Shift" },
    letterUp: { rus: "Shift", en: "Shift" },
    function: empty,
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 0,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyZ",
    letter: { rus: "я", en: "z" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyX",
    letter: { rus: "ч", en: "x" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 2,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyC",
    letter: { rus: "с", en: "c" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 3,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyV",
    letter: { rus: "м", en: "v" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 4,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyB",
    letter: { rus: "и", en: "b" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 5,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyN",
    letter: { rus: "т", en: "n" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 6,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "KeyM",
    letter: { rus: "ь", en: "m" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 7,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Comma",
    letter: { rus: "б", en: "," },
    letterUp: { rus: "Б", en: "<" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 8,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Period",
    letter: { rus: "ю", en: "." },
    letterUp: { rus: "Ю", en: ">" },
  },
  {
    width: width_base,
    height: height_base,
    style: style_base_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 9,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Slash",
    letter: { rus: ".", en: "/" },
    letterUp: { rus: ",", en: "?" },
  },
  // {
  //   width: width_base,
  //   height: height_base,
  //   x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 10,
  //   y: gap + (height_base + gap) * 3,
  //   x_shadow: 0,
  //   y_shadow: 0,
  //   x_delta: 0,
  //   y_delta: 0,
  //   code: "ArrowUp",
  //   letter: "up",
  // },
  {
    width: width_base * 3.2,
    height: height_base,
    style: style_space_button,
    x: gap * 2.5 + width_base * 2.5 + (width_base + gap) * 10,
    y: gap + (height_base + gap) * 3,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ShiftRight",
    letter: { rus: "Shift", en: "Shift" },
    letterUp: { rus: "Shift", en: "Shift" },
    function: empty,
  },
  //////////////  5 ряд /////////////////////////
  {
    width: width_base * 1.5,
    height: height_base,
    style: style_space_button,
    x: gap,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ControlLeft",
    letter: { rus: "Ctrl", en: "Ctrl" },
    letterUp: { rus: "Ctrl", en: "Ctrl" },
    function: empty,
  },
  {
    width: width_base,
    height: height_base,
    style: style_space_button,
    x: gap * 2 + width_base * 1.5 + (width_base + gap) * 0,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "AltLeft",
    letter: { rus: "Alt", en: "Alt" },
    letterUp: { rus: "Alt", en: "Alt" },
    function: empty,
  },
  {
    width: width_base * 1.5,
    height: height_base,
    style: style_space_button,
    x: gap * 2 + width_base * 1.5 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "MetaLeft",
    letter: { rus: "Win", en: "Win" },
    letterUp: { rus: "Win", en: "Win" },
    function: empty,
  },
  {
    width: width_base * 5.95,
    height: height_base,
    style: style_space_button,
    x: gap * 3 + width_base * 1.5 * 2 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "Space",
    letter: { rus: " ", en: " " },
  },
  {
    width: width_base * 1.5,
    height: height_base,
    style: style_space_button,
    x: gap * 4 + width_base * 1.5 * 2 + width_base * 5.95 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "MetaRight",
    letter: { rus: "Win", en: "Win" },
    letterUp: { rus: "Win", en: "Win" },
    function: empty,
  },
  {
    width: width_base,
    height: height_base,
    style: style_space_button,
    x: gap * 5 + width_base * 1.5 * 3 + width_base * 5.95 + (width_base + gap) * 1,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "AltRight",
    letter: { rus: "Alt", en: "Alt" },
    letterUp: { rus: "Alt", en: "Alt" },
    function: empty,
  },
  {
    width: width_base,
    height: height_base / 2,
    style: style_space_button,
    x: gap * (5 + 1.8) + width_base * 1.5 * 3 + width_base * 5.95 + (width_base + gap) * 2,
    y: gap + (height_base + gap) * 4 + height_base / 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ArrowLeft",
    rotate: 360,
    // letter: { rus: "ArrowLeft", en: "ArrowLeft" },
    // letterUp: { rus: "Alt", en: "Alt" },
    function: goLeft,
  },
  {
    width: width_base,
    height: height_base / 2,
    style: style_space_button,
    x: gap * (5 + 1.8 * 2) + width_base * 1.5 * 3 + width_base * 5.95 + (width_base + gap) * 3,
    y: gap + (height_base + gap) * 4,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ArrowUp",
    rotate: 90,
    // letter: { rus: "", en: "" },
    function: goUpDown,
  },
  {
    width: width_base,
    height: height_base / 2,
    style: style_space_button,
    x: gap * (5 + 1.8 * 2) + width_base * 1.5 * 3 + width_base * 5.95 + (width_base + gap) * 3,
    y: gap + (height_base + gap) * 4 + height_base / 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ArrowDown",
    rotate: -90,
    // letter: { rus: "", en: "" },
    function: goUpDown,
  },
  {
    width: width_base,
    height: height_base / 2,
    style: style_space_button,
    x: gap * (5 + 1.8 * 3) + width_base * 1.5 * 4.5 + width_base * 5.95 + (width_base + gap) * 2,
    y: gap + (height_base + gap) * 4 + height_base / 2,
    x_shadow: 0,
    y_shadow: 0,
    x_delta: 0,
    y_delta: 0,
    code: "ArrowRight",
    rotate: 180,
    // letter: { rus: "", en: "" },
    function: goRight,
  },
];
